export const flatLessons = [
    // --- UNIT I: SCIENCE OF MATERIALS ---
    { id: 1, unitId: 1, chapterId: 1, title: "Lesson 1: Scientific Models", type: "lesson" },
    { id: 2, unitId: 1, chapterId: 1, title: "Lesson 2: Measurements and Data Organization in Science", type: "lesson" },
    { id: 3, unitId: 1, chapterId: 1, title: "Lesson 3: Common Laboratory Tools, Equipment, and Wares", type: "lesson" },
    { id: 4, unitId: 1, chapterId: 1, title: "Lesson 4: Doing Scientific Investigations", type: "lesson" },
    { id: 5, unitId: 1, chapterId: 1, title: "Technology in Focus", type: "special" },
    { id: 6, unitId: 1, chapterId: 1, title: "Chapter Review", type: "review" },
    { id: 7, unitId: 1, chapterId: 1, title: "Activity 1: Measurement of Some Physical Quantities", type: "activity" },
    { id: 8, unitId: 1, chapterId: 1, title: "Chapter Test", type: "test" },

    { id: 9, unitId: 1, chapterId: 2, title: "Lesson 1: The Particles of Matter", type: "lesson" },
    { id: 10, unitId: 1, chapterId: 2, title: "Lesson 2: The Particle Nature of the Three States of Matter", type: "lesson" },
    { id: 11, unitId: 1, chapterId: 2, title: "Technology in Focus", type: "special" },
    { id: 12, unitId: 1, chapterId: 2, title: "Chapter Review", type: "review" },
    { id: 13, unitId: 1, chapterId: 2, title: "Activity 2: The Particle Nature of Matter", type: "activity" },
    { id: 14, unitId: 1, chapterId: 2, title: "Chapter Test", type: "test" },
    { id: 15, unitId: 1, chapterId: 2, title: "STEM Challenge", type: "stem" },

    { id: 16, unitId: 1, chapterId: 3, title: "Lesson 1: The Nature of Solutions", type: "lesson" },
    { id: 17, unitId: 1, chapterId: 3, title: "Lesson 2: Solubility and Saturation", type: "lesson" },
    { id: 18, unitId: 1, chapterId: 3, title: "Lesson 3: Factors That Affect Solubility", type: "lesson" },
    { id: 19, unitId: 1, chapterId: 3, title: "Lesson 4: Expressing Concentration of Solutions", type: "lesson" },
    { id: 20, unitId: 1, chapterId: 3, title: "Lesson 5: Practical Examples of Solutions: Acids, Bases, and Salt Solutions", type: "lesson" },
    { id: 21, unitId: 1, chapterId: 3, title: "Technology in Focus", type: "special" },
    { id: 22, unitId: 1, chapterId: 3, title: "Chapter Review", type: "review" },
    { id: 23, unitId: 1, chapterId: 3, title: "Activity 3: Some Factors Affecting Solubility", type: "activity" },
    { id: 24, unitId: 1, chapterId: 3, title: "Activity 4: Percent by Mass of Salt in Aqueous Solutions", type: "activity" },
    { id: 25, unitId: 1, chapterId: 3, title: "Activity 5: Chemistry of Acids and Bases", type: "activity" },
    { id: 26, unitId: 1, chapterId: 3, title: "Chapter Test", type: "test" },
    { id: 27, unitId: 1, chapterId: 3, title: "STEM Challenge", type: "stem" },

    // --- UNIT II: LIFE SCIENCE ---
    { id: 28, unitId: 2, chapterId: 4, title: "Lesson 1: The Microscope: Parts and Function", type: "lesson" },
    { id: 29, unitId: 2, chapterId: 4, title: "Lesson 2: The Cell: The Basic Unit of Life", type: "lesson" },
    { id: 30, unitId: 2, chapterId: 4, title: "Technology in Focus", type: "special" },
    { id: 31, unitId: 2, chapterId: 4, title: "Chapter Review", type: "review" },
    { id: 32, unitId: 2, chapterId: 4, title: "Activity 6: Parts of a Compound Microscope", type: "activity" },
    { id: 33, unitId: 2, chapterId: 4, title: "Activity 7: Focusing Specimens under the Compound Microscope", type: "activity" },
    { id: 34, unitId: 2, chapterId: 4, title: "Chapter Test", type: "test" },
    { id: 35, unitId: 2, chapterId: 4, title: "STEM Challenge", type: "stem" },

    { id: 36, unitId: 2, chapterId: 5, title: "Lesson 1: The Cellular Reproduction", type: "lesson" },
    { id: 37, unitId: 2, chapterId: 5, title: "Lesson 2: Perpetuation of Organisms", type: "lesson" },
    { id: 38, unitId: 2, chapterId: 5, title: "Technology in Focus", type: "special" },
    { id: 39, unitId: 2, chapterId: 5, title: "Chapter Review", type: "review" },
    { id: 40, unitId: 2, chapterId: 5, title: "Activity 8: Meiosis: Modeling Crossing-Over", type: "activity" },
    { id: 41, unitId: 2, chapterId: 5, title: "Activity 9: Sexual Reproduction in Plants", type: "activity" },
    { id: 42, unitId: 2, chapterId: 5, title: "Chapter Test", type: "test" },

    { id: 43, unitId: 2, chapterId: 6, title: "Lesson 1: Levels of Biological Organization", type: "lesson" },
    { id: 44, unitId: 2, chapterId: 6, title: "Lesson 2: Energy Flow in an Ecosystem", type: "lesson" },
    { id: 45, unitId: 2, chapterId: 6, title: "Technology in Focus", type: "special" },
    { id: 46, unitId: 2, chapterId: 6, title: "Chapter Review", type: "review" },
    { id: 47, unitId: 2, chapterId: 6, title: "Activity 10: Creating a Mini-Pond Ecosystem", type: "activity" },
    { id: 48, unitId: 2, chapterId: 6, title: "Chapter Test", type: "test" },
    { id: 49, unitId: 2, chapterId: 6, title: "STEM Challenge", type: "stem" },

    // --- UNIT III: FORCE, MOTION, AND ENERGY ---
    { id: 50, unitId: 3, chapterId: 7, title: "Lesson 1: Force and Interaction", type: "lesson" },
    { id: 51, unitId: 3, chapterId: 7, title: "Lesson 2: Net Force", type: "lesson" },
    { id: 52, unitId: 3, chapterId: 7, title: "Technology in Focus", type: "special" },
    { id: 53, unitId: 3, chapterId: 7, title: "Chapter Review", type: "review" },
    { id: 54, unitId: 3, chapterId: 7, title: "Activity 11: Measuring Forces", type: "activity" },
    { id: 55, unitId: 3, chapterId: 7, title: "Chapter Test", type: "test" },

    { id: 56, unitId: 3, chapterId: 8, title: "Lesson 1: Basic Concepts of Motion", type: "lesson" },
    { id: 57, unitId: 3, chapterId: 8, title: "Lesson 2: Uniform Motion", type: "lesson" },
    { id: 58, unitId: 3, chapterId: 8, title: "Technology in Focus", type: "special" },
    { id: 59, unitId: 3, chapterId: 8, title: "Chapter Review", type: "review" },
    { id: 60, unitId: 3, chapterId: 8, title: "Activity 12: Factors Affecting Motion in Toy Cars", type: "activity" },
    { id: 61, unitId: 3, chapterId: 8, title: "Chapter Test", type: "test" },
    { id: 62, unitId: 3, chapterId: 8, title: "STEM Challenge", type: "stem" },

    { id: 63, unitId: 3, chapterId: 9, title: "Lesson 1: Basic Concepts of Energy and Temperature", type: "lesson" },
    { id: 64, unitId: 3, chapterId: 9, title: "Lesson 2: Modes of Heat Transfer", type: "lesson" },
    { id: 65, unitId: 3, chapterId: 9, title: "Lesson 3: Saving Energy Efficiency", type: "lesson" },
    { id: 66, unitId: 3, chapterId: 9, title: "Technology in Focus", type: "special" },
    { id: 67, unitId: 3, chapterId: 9, title: "Chapter Review", type: "review" },
    { id: 68, unitId: 3, chapterId: 9, title: "Activity 13: Particles in Motion", type: "activity" },
    { id: 69, unitId: 3, chapterId: 9, title: "Chapter Test", type: "test" },
    { id: 70, unitId: 3, chapterId: 9, title: "STEM Challenge", type: "stem" },

    // --- UNIT IV: EARTH AND SPACE SCIENCE ---
    { id: 71, unitId: 4, chapterId: 10, title: "Lesson 1: Earthquakes along Faults", type: "lesson" },
    { id: 72, unitId: 4, chapterId: 10, title: "Lesson 2: Measuring Earthquakes", type: "lesson" },
    { id: 73, unitId: 4, chapterId: 10, title: "Lesson 3: Earthquake Preparedness", type: "lesson" },
    { id: 74, unitId: 4, chapterId: 10, title: "Technology in Focus", type: "special" },
    { id: 75, unitId: 4, chapterId: 10, title: "Chapter Review", type: "review" },
    { id: 76, unitId: 4, chapterId: 10, title: "Activity 14: Simulation of an Earthquake", type: "activity" },
    { id: 77, unitId: 4, chapterId: 10, title: "Chapter Test", type: "test" },
    { id: 78, unitId: 4, chapterId: 10, title: "STEM Challenge", type: "stem" },

    { id: 79, unitId: 4, chapterId: 11, title: "Lesson 1: The Earth's Atmosphere", type: "lesson" },
    { id: 80, unitId: 4, chapterId: 11, title: "Lesson 2: Movement in the Atmosphere", type: "lesson" },
    { id: 81, unitId: 4, chapterId: 11, title: "Technology in Focus", type: "special" },
    { id: 82, unitId: 4, chapterId: 11, title: "Chapter Review", type: "review" },
    { id: 83, unitId: 4, chapterId: 11, title: "Activity 15: Uneven Heating of Earth's Surface", type: "activity" },
    { id: 84, unitId: 4, chapterId: 11, title: "Activity 16: Amount of Water Vapor in the Air", type: "activity" },
    { id: 85, unitId: 4, chapterId: 11, title: "Chapter Test", type: "test" },
    { id: 86, unitId: 4, chapterId: 11, title: "STEM Challenge", type: "stem" },

    { id: 87, unitId: 4, chapterId: 12, title: "Lesson 1: Earth's Motions", type: "lesson" },
    { id: 88, unitId: 4, chapterId: 12, title: "Lesson 2: Seasons in the Philippines", type: "lesson" },
    { id: 89, unitId: 4, chapterId: 12, title: "Technology in Focus", type: "special" },
    { id: 90, unitId: 4, chapterId: 12, title: "Chapter Review", type: "review" },
    { id: 91, unitId: 4, chapterId: 12, title: "Activity 17: Earth's Seasons", type: "activity" },
    { id: 92, unitId: 4, chapterId: 12, title: "Chapter Test", type: "test" }
]